version: '3.1'

services:

    consignment-cli:
        build: ./consignment-cli
        container_name: consignment-cli
        depends_on: 
            - consignment-service
            - vessel-service

    consignment-service:
        build: ./consignment-service
        container_name: consignment-service
        ports:
            - 50051:50051
        depends_on:
            - mongodb
        environment:
            DB_HOST: "mongodb://localhost:27017"

    vessel-service:
        build: ./vessel-service
        container_name: vessel-service
        ports:
            - 50052:50051
        depends_on:
            - mongodb
        environment:
            DB_HOST: "mongodb://localhost:27017"

    user-service:
        build: ./user-service
        ports:
            - 50053:50051
        environment:
            DB_NAME: "postgres"
            DB_HOST: "localhost"
            DB_PORT: "5432"
            DB_USER: "postgres"
            DB_PASSWORD: ""
        depends_on:
            - postgres_db
        network_mode: host

    user-cli:
        build: ./user-cli
        container_name: user-cli
        depends_on: 
            - user-service

    email-service:
        build: ./email-service
        container_name: email-service
        depends_on: 
            - user-service
          
    postgres_db:
        image: postgres
        ports:
            - 5432:5432
        network_mode: host

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        network_mode: host
    
    micro:
        image: micro/micro
        environment:
            MICRO_REGISTRY: "etcd"
            MICRO_API_HANDLER: "rpc"
        ports:
            - 8080:8080
        depends_on: 
            - etcd
        command: --registry_address=http://localhost:2379 api
        network_mode: host
    
    etcd:
        image: bitnami/etcd
        ports:
            - 2379:2379
            - 2380:2380
        environment:
            ALLOW_NONE_AUTHENTICATION: "yes"
            ETCD_ADVERTISE_CLIENT_URLS: "http://localhost:2379"
            # ETCD_LISTEN_CLIENT_URLS: "http://etcd:2379"
            ETCD_ADVERTISE_PEER_URLS: "http://localhost:2380"
            # ETCD_LISTEN_PEER_URLS: "http://etcd:2380"
        network_mode: host
        # volumes:
        #     - ./etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
        
# volumes:
#     etcd_data:
#         driver: local

# networks:
#     backend:
#         driver: bridge