version: '3.1'

services:

    consignment-cli:
        build: ./consignment-cli
        container_name: consignment-cli
        depends_on: 
            - consignment-service
            - vessel-service
        networks: 
            - backend

    consignment-service:
        build: ./consignment-service
        container_name: consignment-service
        ports:
            - 50051:50051
        depends_on:
            - mongodb
        environment:
            MICRO_ADDRESS: ":50051"
            DB_HOST: "mongodb://mongodb:27017"
        networks: 
            - backend

    vessel-service:
        build: ./vessel-service
        container_name: vessel-service
        ports:
            - 50052:50051
        depends_on:
            - mongodb
        environment:
            MICRO_ADDRESS: ":50051"
            DB_HOST: "mongodb://mongodb:27017"
        networks: 
            - backend

    user-service:
        build: ./user-service
        ports:
            - 50053:50051
        environment:
            MICRO_ADDRESS: ":50051"
            DB_NAME: "postgres"
            DB_HOST: "postgres_db"
            DB_PORT: "5432"
            DB_USER: "postgres"
            DB_PASSWORD: ""
        depends_on:
            - postgres_db
        networks: 
            - backend

    user-cli:
        build: ./user-cli
        container_name: user-cli
        depends_on: 
            - user-service
        networks: 
            - backend

    email-service:
        build: ./email-service
        container_name: email-service
        depends_on: 
            - user-service
        networks: 
            - backend
          
    postgres_db:
        image: postgres
        ports:
            - 5432:5432
        networks: 
            - backend

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        networks: 
            - backend
networks:
    backend: